### ISSUE TITLE
Does not find any labels

### ISSUE THREAD

**Issue by francais01** [jenkinsci/github-label-filter-plugin#3]
I've just given this a try and no matter which labels I put on PR's, the Scan Repository Log always says "Has no labels" for every PR. We are using this with GitHub Branch Source Plugin.
Is there any additional debugging I can do or turn on to see where the issue might be?
Thanks!

**Comment by jglick** [comment]
@francais01 are you using GitHub App credentials by any chance?

**Comment by francais01** [comment]
> @francais01 are you using GitHub App credentials by any chance?

Yes, we are.

**Comment by jglick** [comment]
In that case I hope that https://github.com/hub4j/github-api/pull/964 will fix this issue.

**Comment by francais01** [comment]
> In that case I hope that [hub4j/github-api#964](https://github.com/hub4j/github-api/pull/964) will fix this issue.

Sounds good, thanks for working on this. I haven't installed plug-ins from source before, so I may not have a chance to try it out right away, but it looks like someone else tried it out, so maybe it makes it to the normal plug-ins repo soon. 😃

**Comment by francais01** [comment]
Just tested the hpi from @jglick and it solves this problem. I am not sure how you prefer to deal with issues. I can close it now or wait until the fix is in an official release?

**Comment by timja** [comment]
I think we can close this, it's now tracked in github-api

**Comment by jglick** [comment]
1.117
